<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_CNC_Servo" Id="{0744176a-84fd-48f9-b591-7047c81fb408}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CNC_Servo
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>